version: 2.1
commands:
    python-install:
        steps:
            - run: pip install pipenv
            - run: pipenv install
    python-build:
        steps:
            - run: cd acai_aws && pipenv run build
    git-setup:
        steps:
            - run: git config user.email "auto@circleci.com"
            - run: git config user.name "circleci-user"
    git-committ-push:
        steps:
            - run: git checkout main
            - run: git add --all
            - run: git commit -m 'Building & Deploying $CIRCLE_TAG'
            - run: git push
jobs:
    install-build-deploy:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - python-install
            - python-build
            - git-setup
            - git-committ-push
workflows:
    install-build-deploy-workflow:
        jobs:
            - install-build-deploy:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
